apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-metrics-publisher.fullname" . }}
  labels: {{- include "k8s-metrics-publisher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-metrics-publisher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-metrics-publisher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
