name: CI Workflow
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types:
    - published

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Dump variables
      run: |
        echo github.event_name: ${{ github.event_name }}
        echo github.event: '${{ toJson(github.event) }}'
        echo github.event.release.tag_name: ${{ github.event.release.tag_name }}
        echo github.ref: ${{ github.ref }}
        echo github.sha: ${{ github.sha }}
        echo github.head_ref: ${{ github.head_ref }}
        echo github.base_ref: ${{ github.base_reg }}
    - name: Build binary
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o server ./main.go
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Docker build and push
      uses: docker/build-push-action@v4
      with:
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ github.event_name == 'release' && github.event.release.tag_name || format('master-{0}', github.sha) }}
        push: ${{ github.event_name == 'release' || github.ref == 'refs/heads/master' }}
