name: Build code
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build binary
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o server ./main.go
    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=180s
